language: node_js
node_js:
- '8'
- '6'
- '10'
- stable
sudo: false
before_install:
- export PATH=$PATH:`yarn global bin`
- yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
env:
  global:
    secure: CFIJHsjJYfAvY/QLhBnQOg4IaOT3Rrzv0LuYVDu2UyzT4i8a2gMomtoyIX+LakDfpu04QhC/S2QELOcUZVXhi/r2QtGe6qFNekTziDNHKKn7w2fQB0nK8r7lczwsk8DuF1cy4rlnmXX011Zg5dsfu5+L+fYrezQxMbG3MldkRJI=
